import java.util.Arrays;
public class statgen {

    //Java program to generate stats for character creation in 5th edition D&D
	//Stats are generated by rolling 4 six sided die and removing the lowest result
	//to get a number between 3 and 18. This is done six times.
	
	public static void main(String[] args) {
        
		int diceNumber = 4;
		int diceValue = 6;
		
		statgen statGen = new statgen();
		
		//Initiate roll method 6 times to generate each stat.
		for(int i = 1; i <= 6; i++){
        
			statGen.roll(diceNumber, diceValue);
		}
    }

    public void roll(int diceNumber, int diceValue) {
        
		int[] statroll = new int[4];
		int total = 0;
		
		//Roll 1d6 4 times and populate statroll array with results
		for(int i = 1; i < 4; i++){
			
			int result = ((int)(Math.random() * 6) + 1);
			
			statroll[i] = result;
		
		}
		
		//Sort array into ascending order
		Arrays.sort(statroll);
		//Add total of dice rolls, omitting the lowest result at position [0] in the array
		total = statroll[1] + statroll[2] + statroll[3];
		
		//Printing results
		System.out.print(total + " ");
	}
}